# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 15:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_auto_20161123_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='thread',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 23, 15, 2, 18, 918000, tzinfo=utc)),
        ),
    ]
