# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0005_auto_20161124_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
