# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0006_thread_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
