# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=20)),
                ('trade', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
            ],
        ),
    ]
