# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161117_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
